// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "AmneziaWG API",
        "description": "REST API for managing and monitoring AmneziaWG VPN peers and tunnels.",
        "version": "1.0"
    },
    "basePath": "/",
    "paths": {}
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AmneziaWG API",
	Description:      "REST API for managing and monitoring AmneziaWG VPN peers and tunnels.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
